import { Typography } from '@mui/material'
import React from 'react'

function Paragraphs() {
    return (
        <div>
            <Typography sx={{marginBottom:".62rem"}}>A city bustling with dreamers, achievers, go-getters and young souls- Mumbai is not only home to Bollywood but it is a hub for financial services too. Along with that this city is full of high skyscrapers, beaches and picturesque venues. There is no dearth of food vendors, eateries and shopping malls in the city. The capital of Maharashtra, Mumbai is filled with beautiful sea side views and so much more to make this city forever fascinating for everyone. So if you are looking for the best wedding venues in Mumbai, then you have made the right decision. Getting married in Mumbai is a beautiful experience as this city offers a variety of dainty and classy wedding venues for the couples out there who are planning to get married soon. The variety of choices available to choose wedding venues in Mumbai helps you to plan your dream wedding effortlessly.</Typography>
            <Typography sx={{marginBottom:'.62rem'}}>The city has anything and everything you would ever want for your dream wedding. Be it ace designers, market places, inspirations or what not! If you are contemplating the decision to get married in this bustling city, then you shouldn’t have any second thoughts. It is just as perfect as it could be.</Typography>       
            <Typography sx={{marginBottom:'.62rem'}}>If you are thinking what is so exemplary about the wedding venues in Mumbai, we can begin the list with the modern facilities that wedding venues in Mumbai have to offer. There are 671 wedding venues who are there to make your wedding surreal. These venues offer you with unparalleled hospitality and best-in-class services for all your celebrations. So be it a garden wedding venue in Mumbai or a pool facing venue in Mumbai, every venue has unparalleled and premium services to make your D-day special and cherishable.</Typography>
            <Typography sx={{marginBottom:'.62rem'}}>Through WeddingWire App/website you can find any wedding vendors in any city sitting at one place. Be it wedding venues, wedding photographers, bridal makeup artists or bridal jewellery - you can plan for your dream wedding from the comfort of your home. For making your wedding planning an easy sail- all you need to do is visit the WeddingWireIndia website or download the application on your device.</Typography>
            <Typography variant='subtitle2' sx={{margin:'25px 0 10px'}}>How to find the perfect wedding venue in Mumbai?</Typography>
            <Typography sx={{mb:'.62rem'}}>Firstly, you need to be clear what kind of wedding you are looking for, which can be chosen as your wedding theme. For eg: are you looking for a banquet hall for your wedding ceremony or a premium hotel with accommodation available for your guests? Once you have decided the kind of wedding you want, you can now figure out your budget and guest list and then fix and book the most suitable venue in Mumbai. With the help of detailed filters on the WeddingWire India website and app, you can find the venues as per your requirement. For instance, choose the price per plate that serves your budget and choose the guest capacity that you have in mind for the celebration. In Mumbai, there are some alluring options to get married. The wedding venues in Navi Mumbai are also in demand. You can also book temple wedding venues - if you are looking to host your wedding ceremonies in a traditional way. Else, experience the perfect combination of sun, sand, and sea and get yourself treated with world-class hospitality in beach wedding venues in Mumbai. You will also find exemplary venues like farmhouses for organising any of your pre-wedding, wedding or post-wedding functions. There are some lush green farm houses which can be a one-stop destination for all your wedding functions. There are luxe party venues and if you are planning to host a small wedding near Mumbai, then also you will be spoilt for choices.</Typography>
            <Typography sx={{mb:'.62rem'}}>WeddingWireIndia is a trusted wedding planning platform listing where many professional wedding vendors are enlisted. The website and application have varied filters like cost, ratings, locality, etc. Through these filters you can find the wedding venue in Mumbai as per your wish and the one that satiates all your needs. You can check their menu, their prices, ratings and reviews. Through these filters, you can shortlist your favorites vendors. You can contact them directly to get the best quote or book a site visit to further experience the property. There are some fascinating deals too on the website.</Typography>
            <Typography sx={{margin:'25px 0 0px'}} variant="subtitle2">How to find a destination wedding venue near Mumbai as per your budget?</Typography>
            <Typography sx={{mb:'.62rem'}}>Firstly, decide the number of functions that you would want to host and segregate the budget you have for each function. For instance you can plan a different budget for Roka function, Sagan function, Reception, Wedding etc. You can use the budget planning tool which will help you to plan your wedding budget as per your requirement and guest list. After analysing the finances - you can apply filters like Price Per Plate while choosing budget wedding venues near Mumbai/cheap wedding venues in Mumbai. The guest list range starts from 25 and goes till 1000. The price per plate starts from 300 and goes till 5000 or so. The best wedding banquet halls in Mumbai have all the premium services and in-house professionals for all your requirements.</Typography>
        </div>
    )
}

export default Paragraphs
