
//manual sign up
export const SIGNUP_USER_START = 'SIGNUP_USER_START';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';

//register data into firebase
export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
//Login details actions
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

// export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT = "LOGOUT";
// export const LOGOUT_ERROR = "LOGOUT_ERROR";

export const ALERT = "ALERT";

export const GOOGLE_SIGN_IN_START = "GOOGLE_SIGN_IN_START"
export const GOOGLE_SIGN_IN_SUCCESS = "GOOGLE_SIGN_IN_SUCCESS"
export const GOOGLE_SIGN_IN_ERROR = "GOOGLE_SIGN_IN_ERRORL"

export const FACEBOOK_SIGN_IN_START = "FACEBOOK_SIGN_IN_START"
export const FACEBOOK_SIGN_IN_SUCCESS = "FACEBOOK_SIGN_IN_SUCCESS"
export const FACEBOOK_SIGN_IN_ERROR = "FACEBOOK_SIGN_IN_ERROR"

export const GET_HOME_PAGE_START = "GET_HOME_PAGE_START";
export const GET_HOME_PAGE_SUCCESS = "GET_HOME_PAGE_SUCCESS";
export const GET_HOME_PAGE_ERROR = "GET_HOME_PAGE_ERROR";

export const GET_INNER_PAGE_START = "GET_INNER_PAGE_START";
export const GET_INNER_PAGE_SUCCESS = "GET_INNER_PAGE_SUCCESS";
export const GET_INNER_PAGE_ERROR = "GET_INNER_PAGE_ERROR";